export const grayPairs = {
    tomato: "mauve",
    red: "mauve",
    ruby: "mauve",
    crimson: "mauve",
    pink: "mauve",
    plum: "mauve",
    purple: "mauve",
    violet: "mauve",
    iris: "slate",
    indigo: "slate",
    blue: "slate",
    sky: "slate",
    cyan: "slate",
    mint: "sage",
    teal: "sage",
    jade: "sage",
    green: "sage",
    grass: "olive",
    lime: "olive",
    yellow: "sand",
    amber: "sand",
    orange: "sand",
    brown: "sand",
    mauve: "mauve",
    slate: "slate",
    sage: "sage",
    olive: "olive",
    sand: "sand",

  };